version: "3"
services:
  web:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./project:/var/www/html/project
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./log/nginx:/var/log/nginx
      - phpsocket:/dev/shm
    links:
      - php
    networks:
      - app_net
  php:
    image: php/fpm-5.6:v1
    volumes:
      - ./project:/var/www/html/project
      - ./php-fpm.conf:/usr/local/etc/php/5.6/etc/php-fpm.conf
      - ./php.ini:/usr/local/etc/php/5.6/etc/php.ini
      - phpsocket:/dev/shm
    networks: 
      - app_net
  mysql: # 添加 mysql 服务
    image: mysql:5.6
    ports:
      - "3306:3306"
    environment:
      - TZ=Asia/Shanghai # 设置时区
      - MYSQL_ROOT_PASSWORD=root # 设置 root 用户密码
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci # 设置编码
    networks:
      app_net:                # 固定子网ip，网段必须在子网络10.10.*.*
        ipv4_address: 10.10.10.1
networks:    # 配置docker network
  app_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.0.0/16
volumes:
  phpsocket: