version: "3"
services:
  web:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./project:/var/www/html/project
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./log/nginx:/var/log/nginx
      - phpsocket:/dev/shm
    links:
      - php
  php:
    image: php/fpm-5.6:v1
    volumes:
      - ./project:/var/www/html/project
      - ./php-fpm.conf:/usr/local/etc/php/5.6/etc/php-fpm.conf
      - ./php.ini:/usr/local/etc/php/5.6/etc/php.ini
      - phpsocket:/dev/shm
volumes:
  phpsocket: