version: '3'
services:
  nginx:
    image: nginx:latest
    privileged: true
    volumes:
      - phpsocket:/dev/shm
      - ${PROJ_PATH}/proj:/home/www
      - ${DOCKER_PATH}/conf.d:/etc/nginx/conf.d
      - ${DOCKER_PATH}/nginx_conf/fastcgi.conf:/etc/nginx/fastcgi.conf
      - ${DOCKER_PATH}/nginx_conf/nginx.conf:/etc/nginx/nginx.conf
      - ${DOCKER_PATH}/logs:/home/logs
  #  working_dir: /usr/local/bin/entrypoint
  #  entrypoint:
  #    - /usr/local/bin/entrypoint/nginx_entrypoint.sh
    links:
      - backend
    ports:
      - 80:80
  backend:
    image: php7.1:latest
    restart: always
    volumes:
      - phpsocket:/dev/shm
      - ${PROJ_PATH}/proj:/home/www
  #    - ${DOCKER_PATH}/php_conf/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ${DOCKER_PATH}/php_conf/php-fpm.conf:/usr/local/etc/php-fpm.conf
volumes:
  phpsocket: