version: '3'
services:
  nginx:
    image: nginx:latest
    privileged: true
    volumes:
      - phpsocket:/dev/shm
      - /f/hangjiayun_proj/proj:/home/www
      - /f/hangjiayun_proj/conf.d:/etc/nginx/conf.d
      - /f/hangjiayun_proj/nginx_conf/fastcgi.conf:/etc/nginx/fastcgi.conf
      - /f/hangjiayun_proj/nginx_conf/nginx.conf:/etc/nginx/nginx.conf
      - /f/hangjiayun_proj/logs:/home/logs
  #  working_dir: /usr/local/bin/entrypoint
  #  entrypoint:
  #    - /usr/local/bin/entrypoint/nginx_entrypoint.sh
    links:
      - backend
    ports:
      - 80:80
  backend:
    image: php7.1:latest
    volumes:
      - phpsocket:/dev/shm
      - /f/hangjiayun_proj/proj:/home/www
      - /f/hangjiayun_proj/php_conf/www.conf/:/usr/local/etc/php-fpm.d/www.conf
      - /f/hangjiayun_proj/php_conf/php-fpm.conf/:/usr/local/etc/php-fpm.conf
volumes:
  phpsocket: